SELECT SUM(SAL) / COUNT(SAL) "AVRG SAL"
FROM EMP;

SELECT MIN(SAL) "MIN CLERK"
FROM EMP
WHERE JOB = 'CLERK';

SELECT COUNT(*) "PPL IN DEPT 20"
FROM EMP
WHERE DEPTNO = 20;

SELECT JOB, AVG(SAL)
FROM emp
GROUP BY JOB;

SELECT JOB, AVG(SAL)
FROM emp
WHERE NOT JOB = 'MANAGER'
GROUP BY JOB;

SELECT DEPTNO, JOB, AVG(SAL)
FROM emp
GROUP BY DEPTNO, JOB;

SELECT JOB, MAX(SAL)
FROM emp
GROUP BY JOB;

SELECT DEPTNO, AVG(SAL)
FROM emp
GROUP BY DEPTNO
HAVING COUNT(DEPTNO) > 3;

SELECT JOB
FROM EMP
GROUP BY JOB
HAVING AVG(SAL) >= 3000;

SELECT JOB, AVG(SAL), AVG((12 * SAL + NVL(COMM, 0)))
FROM EMP
GROUP BY JOB;

SELECT MAX(SAL) - MIN(SAL) "ROZNICA"
FROM EMP;

SELECT DEPTNO
FROM EMP
GROUP BY DEPTNO
HAVING COUNT(DEPTNO) > 3;

SELECT MAX(COUNT(*))
FROM EMP
GROUP BY EMPNO;

SELECT MIN(SAL), MGR
FROM EMP
GROUP BY MGR
HAVING MIN(SAL) >= 1000
ORDER BY MIN(SAL);

SELECT COUNT(*)
FROM EMP
         INNER JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO
WHERE dept.loc = 'DALLAS';

SELECT GRADE, MAX(SAL)
FROM SALGRADE
         INNER JOIN emp ON EMP.SAL > SALGRADE.LOSAL AND EMP.SAL < SALGRADE.HISAL
GROUP BY GRADE;

SELECT SAL
FROM EMP
GROUP BY SAL
HAVING COUNT(SAL) > 1;

SELECT GRADE, AVG(SAL)
FROM SALGRADE
         INNER JOIN emp ON EMP.SAL > SALGRADE.LOSAL AND EMP.SAL < SALGRADE.HISAL
WHERE GRADE = 2
GROUP BY GRADE;

SELECT MGR, COUNT(MGR)
FROM EMP
WHERE MGR IS NOT NULL
GROUP BY MGR;

SELECT GRADE, SUM(SAL)
FROM SALGRADE
         INNER JOIN emp ON EMP.SAL > SALGRADE.LOSAL AND EMP.SAL < SALGRADE.HISAL
WHERE GRADE = 1
GROUP BY GRADE;