SELECT *
FROM EMP,
     DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO;

SELECT *
FROM EMP
         INNER JOIN DEPT ON DEPT.DEPTNO = EMP.DEPTNO;

SELECT ENAME, DNAME
FROM EMP,
     DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO
ORDER BY ENAME;

SELECT ENAME, EMP.DEPTNO, DNAME
FROM EMP,
     DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO;

SELECT ENAME, LOC, DNAME
FROM EMP,
     DEPT
WHERE SAl > 1500
  AND EMP.DEPTNO = DEPT.DEPTNO;

SELECT ENAME, JOB, SAL, GRADE
FROM EMP,
     SALGRADE
WHERE SAL BETWEEN LOSAL AND HISAL;

SELECT *
FROM EMP,
     SALGRADE
WHERE SAL BETWEEN SALGRADE.LOSAL AND SALGRADE.HISAL
  AND GRADE = 3;

SELECT *
FROM EMP,
     DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO
  AND LOC = 'DALLAS';

SELECT ENAME, DNAME, GRADE
FROM EMP
         INNER JOIN DEPT D ON D.DEPTNO = EMP.DEPTNO
         INNER JOIN SALGRADE ON EMP.SAL BETWEEN LOSAL AND HISAL;

SELECT *
FROM DEPT
         LEFT JOIN EMP E ON DEPT.DEPTNO = E.DEPTNO;

SELECT *
FROM DEPT
         RIGHT JOIN EMP E ON DEPT.DEPTNO = E.DEPTNO;


SELECT ENAME, DEPTNO
FROM EMP
WHERE DEPTNO = 20
UNION
SELECT '', DEPTNO
FROM EMP
WHERE DEPTNO = 30;

SELECT DISTINCT JOB
FROM EMP
WHERE DEPTNO IN (10, 30);

SELECT JOB
FROM EMP
WHERE DEPTNO = 10
INTERSECT
SELECT JOB
FROM EMP
WHERE DEPTNO = 30;

SELECT JOB
FROM EMP
WHERE DEPTNO = 10
MINUS
SELECT JOB
FROM EMP
WHERE DEPTNO = 30;

SELECT PRAC.ENAME, PRAC.SAL, SZEF.SAL
FROM EMP PRAC,
     EMP SZEF
WHERE PRAC.MGR = SZEF.EMPNO
  AND PRAC.SAL < SZEF.SAL;

SELECT PRAC.ENAME, SZEF.ENAME
FROM EMP PRAC,
     EMP SZEF
WHERE PRAC.MGR = SZEF.EMPNO
ORDER BY SZEF.ENAME;