SELECT E.ENAME, D.DNAME
FROM EMP E
         INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO;

SELECT *
FROM DEPT
WHERE DEPTNO NOT IN (SELECT EMP.DEPTNO FROM EMP);

SELECT EMPNO, SAL
FROM EMP
WHERE MGR IS NULL
ORDER BY SAL;

SELECT E.ENAME, S.GRADE
FROM EMP E
         INNER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL
         INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
WHERE D.DNAME = 'SALES';

SELECT ENAME, SAL, (SELECT ENAME FROM EMP E2 WHERE E1.MGR = E2.EMPNO)
FROM EMP E1
WHERE SAL = (SELECT MIN(SAL) FROM EMP)
   OR SAL = (SELECT MAX(SAL) FROM EMP);

SELECT DEPT.DEPTNO, DNAME, LOC
FROM DEPT
         INNER JOIN EMP E ON DEPT.DEPTNO = E.DEPTNO
HAVING COUNT(EMPNO) >= 3
GROUP BY DEPT.DEPTNO, DNAME, LOC;

SELECT DEPTNO, AVG(SAL)
FROM EMP
GROUP BY DEPTNO
ORDER BY AVG(SAL) DESC;

SELECT JOB, DEPTNO
FROM EMP
GROUP BY JOB, DEPTNO
HAVING COUNT(*) >= 2;

SELECT ENAME, JOB, SAL
FROM EMP E1
WHERE DEPTNO = (SELECT DEPTNO FROM EMP E2 WHERE E2.ENAME = 'WARD');

SELECT ENAME, SAL
FROM EMP E1
WHERE NOT EXISTS(SELECT * FROM EMP E2 WHERE E2.MGR = E1.EMPNO);